---
- name: Implanta o Docker e configura contêineres para PHP/Apache e PostgreSQL
  hosts: cloud

  roles:
    - docker

  tasks:
    - name: Implanta o Docker com Apache e PHP
      ansible.builtin.include_tasks: tasks/docker/deploy_php_apache.yml
      vars:
        docker_php_apache_port: 8080
        docker_php_apache_volume: /home/docker/php_apache
      tags: docker_php_apache

    - name: Implanta o Docker com PostgreSQL
      ansible.builtin.include_tasks: tasks/docker/deploy_postgres.yml
      vars:
        docker_postgres_port: 54321
        docker_postgres_volume: /home/docker/postgres
        docker_postgres_password: secret
      tags: docker_postgres

- name: Implantação do Apache no contêiner AWS EC2
  hosts: web_development
  remote_user: ubuntu
  become: true
  tasks:
    - name: Inclui o role webserver
      ansible.builtin.include_role:
        name: webserver
      tags: webserver
