---
- name: Tarefas comuns para desktops
  hosts: desktops

  roles:
    - role: ajholanda.googlechrome
      tags: googlechrome
    - libreoffice
    - netbios
    - update
    - user
    - sshserver

- name: Desktops de desenvolvedores
  hosts: devs
  roles:
    - role: ajholanda.vscode
      tags: vscode
  
- hosts: infotech
  roles:
    - role: ajholanda.x2goclient
      tags: x2goclient

- name: Laboratório de informática
  hosts: lab
  roles:
    - power
