---
- name: Exemplo de uso de filtros
  hosts: lab

  vars:
    power_off_minute: 30
    power_off_hour: 22
    power_off_weekday: '*'

  tasks:
    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday }}"
        hour: "{{ power_off_hour | mandatory }}"
        minute: "{{ power_off_minute | mandatory }}"
        user: root
        job: "/sbin/shutdown -h now"
      tags:
       - filter_mandatory
       - never

    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday }}"
        hour: "{{ power_off_hour | mandatory | int }}"
        minute: "{{ power_off_minute | mandatory | int }}"
        user: root
        job: "/sbin/shutdown -h now"
      tags:
       - filter_int
       - never

    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday | default('*') }}"
        hour: "{{ power_off_hour | mandatory | int }}"
        minute: "{{ power_off_minute | mandatory | int }}"
        user: root
        job: "/sbin/shutdown -h now"
      tags:
       - filter_default
       - never

- name: Exemplo do filtro lower
  hosts: webservers
  gather_facts: true

  tasks:
    - name: Instala o Apache
      ansible.builtin.package:
        name: apache2
        state: present
      when: ansible_facts['os_family'] | lower == "debian"
      tags:
        - filter_lower
        - never

- name: Exemplo do filtro join
  hosts: localhost
  gather_facts: false

  vars:
    dnsservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9

  tasks:
    - name: Converte a lista em uma string separada por vírgulas
      ansible.builtin.debug:
        msg: "Os servidores DNS configurados são: {{ dnsservers | join(',') }}"
      tags:
       - filter_join
       - never