---
- name: Exemplo de uso de filtros
  hosts: lab

  vars:
    power_off_minute: 30
    power_off_hour: 22
    power_off_weekday: '*'
    system_groups:
      - audio
      - plugdev
      - netdev
      - users
      - video

  tasks:
    # mandatory
    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday }}"
        hour: "{{ power_off_hour | mandatory }}"
        minute: "{{ power_off_minute | mandatory }}"
        user: root
        job: "/sbin/shutdown -h now"

    # int (data type)
    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday }}"
        hour: "{{ power_off_hour | mandatory | int }}"
        minute: "{{ power_off_minute | mandatory | int }}"
        user: root
        job: "/sbin/shutdown -h now"

    # default
    - name: Cria uma entrada na crontab para desligar o computador
      ansible.builtin.cron:
        name: "shutdown at"
        weekday: "{{ power_off_weekday | default('*') }}"
        hour: "{{ power_off_hour | mandatory | int }}"
        minute: "{{ power_off_minute | mandatory | int }}"
        user: root
        job: "/sbin/shutdown -h now"

    # lower
    - name: Instala o apache
      ansible.builtin.package:
        name: apache2
      when: ansible_distribution | lower == "debian"

    # join
    - name: Cria usuário e adiciona em alguns grupos do sistema
      ansible.builtin.user:
        name: ajh
        comment: "Adriano J. Holanda"
        shell: /bin/bash
        createhome: true
        home: /home/ajh
        groups: "{{ system_groups | join(',') }}"
        append: true
