---
# lint_v1.yml

- name: Informações dos discos e criação de diretórios.
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Retorna a informação de uso dos discos.
      ansible.builtin.command: df -h
      register: disk_usage
      changed_when: false

    - name: Imprime as informações de uso dos discos.
      ansible.builtin.debug:
        var: disk_usage.stdout

    - name: Cria diretórios.
      ansible.builtin.file:
        path: "~/ansible/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - 'files'
        - 'roles'
        - 'tasks'
