---
- name: Instala o Ansible Molecule e o plugin Docker
  hosts: localhost
  connection: local

  roles:
    - docker

  tasks:
    - name: Instala as dependências
      ansible.builtin.apt:
        pkg:
          - python3-pip
          - libssl-dev
      when: ansible_os_family == 'Debian'

    - name: Instala as dependências
      ansible.builtin.dnf:
        name:
          - gcc
          - python3-pip
          - python3-devel
          - openssl-devel
          - python3-libselinux
      when: ansible_os_family == 'RedHat'

    - name: Instala o Ansible Molecule, o plugin Docker e o Testinfra
      ansible.builtin.pip:
        name:
          - molecule
          - molecule-plugins[docker]
          - pytest-testinfra
      notify: Logout warning

  handlers:
    - name: Logout warning
      ansible.builtin.debug:
        msg: "Talvez você tenha que fazer logout e login para usar o Molecule"
