---
- hosts: localhost
  connection: local

  roles:
    - docker

  tasks:
    - name: Instala as dependências
      apt:
        pkg:
          - python3-pip
          - libssl-dev
      when: ansible_os_family == 'Debian'

    - name: Instala as dependências
      dnf:
        name:
          - gcc
          - python3-pip
          - python3-devel
          - openssl-devel
          - python3-libselinux
      when: ansible_os_family == 'RedHat'

    - name: Instala o Ansible Molecule e alguns plugins
      pip:
        name:
          - molecule
          - molecule-plugins[docker]
      register: molecule_install

    - debug:
        msg: "Talvez você tenha que fazer logout e login para usar o Molecule"
      when: molecule_install.changed
