---
- name: Verifica a existência de um arquivo de certificados
  hosts: web.example.net

  tasks:
    - name: Captura o status do arquivo de certificados
      ansible.builtin.stat:
        path: /etc/ssl/certs/ca-certificates.crt
      register: stat_register

    - name: Imprime o conteúdo do registro
      ansible.builtin.debug:
        var: stat_register
