collections:
  - name: ansible.windows
    version: ">=3.2.0"
  - name: chocolatey.chocolatey
    version: ">=1.5.3"
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.windows

roles:
  - name: ajholanda.x2goclient
    version: "1.3.0"
