---
- name: Administra servidores de banco de dados
  hosts: dbservers
  roles:
    - mariadbserver

- name: Administra servidores rsync
  hosts: rsyncservers
  roles:
    - rsyncserver

- name: Carrega roles comuns para servidores
  hosts: servers
  roles:
    - fail2ban
    - sshserver
    - sudo
    - update
