---
- name: Carrega roles comuns para servidores
  hosts: servers
  roles:
    - fail2ban
    - sshserver
    - update
    - user

- name: Administra servidores de banco de dados
  hosts: dbservers
  roles:
    - mariadb

- name: Administra servidores rsync
  hosts: rsyncservers
  roles:
    - rsyncserver

- name: Administra servidores web
  hosts: webservers
  roles:
    - webserver
