---
- name: Exemplo de uso de etiquetas no Ansible
  hosts: localhost
  connection: local

  tasks:
    - name: Etiqueta always
      ansible.builtin.debug:
        msg: "Executa (quase) sempre"
      tags: always

    - name: Etiqueta never
      ansible.builtin.debug:
        msg: "Executa (quase) nunca"
      tags: never, debug

    - name: Sem etiqueta
      ansible.builtin.debug:
        msg: "Tarefa sem etiqueta"
