---
- name: Exemplo de uso de tags no Ansible
  hosts: localhost
  connection: local

  tasks:
    - name: Tag always
      ansible.builtin.debug:
        msg: "Executa (quase) sempre"
      tags: always

    - name: Tag never
      ansible.builtin.debug:
        msg: "Executa (quase) nunca"
      tags: never, debug

    - name: Sem tag
      ansible.builtin.debug:
        msg: "Tarefa sem tag"
