# webserver.yml
---
- name: Administra servidores web
  hosts: webservers

  tasks:
  - name: Instala o apache
    package:
      name: apache2
    tags: webserver, webserver_package

  - name: Habilita e inicializa o apache
    service:
      name: apache2
      enabled: yes
      state: started
    tags:
      - webserver
      - webserver_service

  - name: Copia o arquivo de configuração
    copy:
      src: files/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
    notify:
      - restart apache2
    when: ansible_os_family|lower == "debian"
    tags: webserver, webserver_copy

  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted