# webserver.yml
---
- name: Administra servidores web
  hosts: webservers

  tasks:
    - name: Instala o apache
      ansible.builtin.package:
        name: apache2
      tags: webserver, webserver_package

    - name: Habilita e inicializa o apache
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
      tags:
        - webserver
        - webserver_service

    - name: Copia o arquivo de configuração
      ansible.builtin.copy:
        src: files/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: www-data
        group: www-data
        mode: '0644'
      notify:
        - Restart apache2
      when: ansible_os_family | lower == "debian"
      tags: webserver, webserver_copy

  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
