---
- name: Administra servidores web (Debian)
  hosts: web.example.net
  roles:
    - webserver_debian
  tags:
    - webserver_debian
    - never

- name: Administra servidores web
  hosts: webservers
  roles:
    - webserver
