---
- name: Administra servidores web
  hosts: webservers

  tasks:
    - name: Inclui as tarefas a família {{ ansible_os_family }}
      ansible.builtin.include_tasks: "tasks/webserver-{{ ansible_os_family }}.yml"
