---
- name: Administra as estações de trabalho
  hosts: workstations

  roles:
    - fail2ban
    - devtools
    - role: ajholanda.googlechrome
      tags: googlechrome
    - libreoffice
    - nvidia
    - remotedesktop
    - sshserver
    - update
    - user
    - role: ajholanda.vscode
      tags: vscode
