- name: Garante a existência do usuário ajh
  ansible.windows.win_user:
    name: ajh
    password: "{{ user_ajh_password | mandatory }}"
    state: present
    groups:
      - Administrators
      - Users
  tags: user

- name: Habilita o usuário Administrador
  ansible.windows.win_user:
    name: Administrador
    password: "{{ user_administrator_password | mandatory }}"
    account_disabled: false
  tags: user
