- name: Garante a existência do usuário ajh
  ansible.windows.win_user:
    name: ajh
    password: senh@@jH
    state: present
    groups:
      - Administrators
      - Users
  tags: user

- name: Habilita o usuário Administrador
  ansible.windows.win_user:
    name: Administrador
    password: senh@@dm1n
    account_disabled: false
  tags: user
