---
- name: Agenda desligamento automático diário
  community.windows.win_scheduled_task:
    name: "LabShutdown"
    description: "Desligamento automático"
    actions:
      - path: shutdown.exe
        arguments: "/s /f /t 60"
    triggers:
      - type: daily
        start_boundary: |
          2026-01-28T{{ power_shutdown_hour | int }}:{{ power_shutdown_minute | int }}:00
    username: SYSTEM
    run_level: highest
  tags: power

- name: Ativar plano equilibrado
  ansible.windows.win_command: >
    powercfg /setactive SCHEME_BALANCED
  tags: power

- name: Configura o tempo limite de suspensão no Windows
  ansible.windows.win_command: >
    powercfg /change standby-timeout-ac {{ ( power_suspend_timeout | int ) // 60 }}
  tags: power

- name: Desativar hibernação
  ansible.windows.win_command: >
    powercfg /hibernate off
  tags: power