---
- name: Instala o programa rsync
  ansible.builtin.package:
    name: rsync
  tags: rsyncserver

- name: Copia arquivo com usuários e senhas
  ansible.builtin.copy:
    src: rsyncd.secrets
    dest: /etc/
    owner: root
    mode: "0600"
  tags: rsyncserver
