---
_webserver_confdir_default: /etc/httpd/conf.d
_webserver_group_default: apache
_webserver_logdir_default: /var/log/httpd
_webserver_package_default: httpd
_webserver_service_default: httpd
_webserver_user_default: apache
# BEGIN REPO-ONLY
_webserver_ports_conf_default: "/etc/httpd/conf/httpd.conf"
# END REPO-ONLY
