---
- name: Instala o pacote unattended-upgrades
  ansible.builtin.package:
    name: unattended-upgrades
  tags: update

- name: Habilita e inicializa o serviço unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
    state: started
  tags: update

- name: Configura notificações por email
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '//Unattended-Upgrade::Mail\s+"";'
    line: 'Unattended-Upgrade::Mail "ajh@example.net";'
    backup: true
  notify: Restart unattended-upgrades
  when: >
    inventory_hostname in groups['servers']
    or inventory_hostname in groups['workstations']
  tags: update
