---
- name: Instala o pacote dnf-automatic
  ansible.builtin.package:
    name: dnf-automatic
  tags: update

- name: Habilita e inicializa o serviço dnf-automatic
  ansible.builtin.service:
    name: dnf-automatic
    enabled: true
    state: started
  tags: update
