---
- name: Instala o SSSD
  ansible.builtin.package:
    name: sssd
  when: ansible_facts['system'] | lower == 'linux'
  tags: sssd

- name: Copia o arquivo de configuração
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart sssd
  when: ansible_facts['system'] | lower == 'linux'
  tags: sssd

- name: Habilita e inicia o serviço
  ansible.builtin.service:
    name: sssd
    enabled: true
    state: started
  when: ansible_facts['system'] | lower == 'linux'
  tags: sssd
