---
- name: Instala o banco de dados MariaDB
  ansible.builtin.package:
    pkg:
      - mariadb-client
      - mariadb-common
      - mariadb-server
      - python3-mysqldb
  tags: mariadbserver

- name: Adiciona usuário com privilégios administrativos
  community.mysql.mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: '*.*:ALL'
  tags: mariadbserver
