---
- name: Copia o script de verificação do firewall SSH para o sistema
  ansible.windows.win_copy:
    dest: "C:\\Windows\\Ensure-SSHFirewallRule.ps1"
    content: |
      # Verifica se a regra do firewall SSH está presente.
      $rule = Get-NetFirewallRule -Name "OpenSSH Server (sshd)" -ErrorAction SilentlyContinue

      if (-not $rule) {
          Write-Output "SSH rule missing. Adding it..."
          New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
      } else {
          Write-Output "SSH firewall rule is already present."
      }
  tags: sshserver

- name: Configura a regra do firewall SSH para ser executada na inicialização do sistema
  ansible.windows.win_powershell:
    script: |
      $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File C:\\Windows\\Ensure-SSHFirewallRule.ps1"
      $trigger = New-ScheduledTaskTrigger -AtStartup
      $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

      Register-ScheduledTask -TaskName "EnsureSSHFirewallRule" -Action $action -Trigger $trigger -Principal $principal
  tags: sshserver