---
- name: Copia o arquivo de configuração para o servidor ssh
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd
  tags: sshserver
