---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    # Molecule create directory with root ownership, the problem
    # is that during deletion, for some reason vagrant user is
    # used to wipe the directorycreated.
    - name: Fix Ansible temporary directory ownership
      shell: chown -R vagrant:vagrant /home/vagrant/.ansible/

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: 0600
      when: server.changed | default(false) | bool  # noqa no-handler
