---
- name: Prepara o sistema para o teste
  hosts: all
  gather_facts: false

  tasks:
    - name: Instala os pacotes necessários para o teste
      ansible.builtin.package:
        update_cache: true
        name: curl
