---
- name: Inclui tarefas para a distribuição {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  tags: docker
  when: ansible_distribution | lower == 'ubuntu'
