---
- name: Instala o apache2
  ansible.builtin.package:
    update_cache: true
    name: apache2

- name: Habilita e inicializa o apache2
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started

- name: Copia a página teste
  ansible.builtin.copy:
    src: index.html
    owner: www-data
    group: www-data
    mode: "0644"
    dest: /var/www/html/

- name: Copia o arquivo de configuração
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/apache2/sites-available/site.conf
    owner: www-data
    group: www-data
    mode: "0644"
  notify: Restart apache2

- name: Habilita a configuração do site via link simbólico
  ansible.builtin.file:
    src: /etc/apache2/sites-available/site.conf
    dest: /etc/apache2/sites-enabled/site.conf
    state: link
  notify: restart apache2
