---
- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart dnf-automatic
  ansible.builtin.service:
    name: dnf-automatic
    state: restarted
