---
- name: Garante que a imagem com o PHP e Apache esteja presente
  community.docker.docker_image:
    name: "php:apache"
    source: pull
  tags: docker_php_apache

- name: Garante que o diretório de armazenamento de dados exista
  ansible.builtin.file:
    path: "{{ docker_php_apache_volume | mandatory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: docker_php_apache

- name: Garante que o contêiner PHP esteja em execução
  community.docker.docker_container:
    name: "php_apache"
    image: "php:apache"
    state: started
    ports:
      - "{{ docker_php_apache_port | mandatory }}:80"
    volumes:
      - "{{ docker_php_apache_volume | mandatory }}:/var/www/html"
  tags: docker_php_apache
