---
- name: Garante que a imagem Docker com o PostgreSQL esteja presente  # 1.
  community.docker.docker_image:
    name: "postgres:latest"
    source: pull
  tags: docker_postgres

- name: Cria o diretório raiz do PostgreSQL  # 2.
  ansible.builtin.file:
    path: "{{ docker_postgres_volume | mandatory }}"
    state: directory
    owner: root
    group: docker
    mode: '0775'
  tags: docker_postgres

- name: Garante a execução do contêiner Docker com o PostgreSQL  # 3.
  community.docker.docker_container:
    name: "postgres"
    image: "postgres:latest"
    state: started
    ports:
      - "{{ docker_postgres_port | default(5432) }}:5432"
    volumes:
      - "{{ docker_postgres_volume }}:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ docker_postgres_user | default('postgres') }}"
      POSTGRES_PASSWORD: "{{ docker_postgres_password | mandatory }}"
      POSTGRES_DB: "{{ docker_postgres_db | default('postgres') }}"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "{{ docker_postgres_initdb_args | default('') }}"
  tags: docker_postgres
