---
- name: Descobrir subchaves de interfaces NetBT
  ansible.windows.win_shell: |
    (Get-ChildItem "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces").PSChildName
  register: netbt_interfaces
  tags: netbios

- name: Desabilitar NetBIOS over TCP/IP em todas as interfaces
  ansible.windows.win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\\Interfaces\\{{ item }}"
    name: NetbiosOptions
    data: 2
    type: dword
  loop: "{{ netbt_interfaces.stdout_lines }}"
  tags: netbios