name: Fluxo de testes

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/**'
      - 'molecule/**'
      - 'roles/**'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixa o código
        uses: actions/checkout@v4

      - name: Configura o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instala Ansible, Molecule, plugin Docker e Testinfra
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule-plugins[docker] ansible-lint pytest-testinfra

      - name: Executa os testes com o Molecule
        run: |
          molecule test